config/routes.rb
Rails.application.routes.draw do
  root 'main#home'
  get '/home', to: 'main#home'
  get '/about', to: 'main#about'
  get '/contact', to: 'main#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @categories = Category.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_footer.html.erb
  <%= stylesheet_link_tag "style.css" %>
  <footer class="footer">
    <div class="container text-center">
      <span class="footer-text">Copyright © 2018 | All Rights Reserved</span>
    </div>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">My Developer Site with Rails</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "ABOUT", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "CONTACT", contact_path, class: "nav-link" %>
        </li>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Developer Website With Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/main/about.html.erb
<body>
    <br>
    <br>
    <main>
        <div class="container-fluid text-center">
            <div class="row">
                <div class="col-sm-12 ">
                  <%= image_tag "programmer.gif" %>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div class="container">
            <div id="about">
                <div class="container">
                <h1 class="text-center aboutHeading">About Me</h1>
                <p class="aboutPG text-justify">
                    Welcome to my site! I am a professional with expertise in Javascript, Python, and Ruby programming languages, as well as data analytics, system architecture, web security, and system admin skills.<br>

                    My primary focus is on delivering high-quality, reliable, and scalable web applications that meet the needs of our clients. We use a variety of tools and technologies to achieve this, including Javascript, Python, and Ruby, as well as data analytics and system architecture techniques to ensure that our systems are optimized for performance and reliability.

                    In addition to our technical skills, we also have a strong focus on web security, ensuring that our systems are secure and protected from potential threats. We also have extensive experience in system administration, allowing us to manage and maintain complex systems with ease.

                    Overall, our team is dedicated to providing top-notch development services to our clients, and we look forward to working with you on your next project. 
                    <br>Thank you for considering me for your development needs!
                </p>
                </div>
            </div>
        </div>
    </main>
</body>

app/views/main/contact.erb
<body>
    <main>
        <br>
        <br>
        <div class="container-fluid text-center">
            <div class="row">
                <div class="col-sm-12">
                    <%= image_tag "contact.gif" %>
                </div>
            </div>
        </div>
        <div class="container-sm">
        </div>
        <br>
            <div class="container">
                <!--Contact Section - I used php to get this working with my server-->
                <div id="contact">
                    <div class="container">
                    <h1 class="text-center aboutHeading">Contact Me</h1>
                    <form>
                        <div class="form-group">
                        <label for="formGroupExampleInput">Name</label>
                        <input type="text" class="form-control" id="formGroupExampleInput">
                        </div>
                        <div class="form-group">
                        <label for="exampleFormControlInput1">Email address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1">
                        </div>
                        <div class="form-group">
                        <label for="exampleFormControlTextarea1">Message</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                        <div>
                        <br>
                        <button type="submit" class="btn btn-info mb-2" id="button">Submit</button>
                        </div>
                    </form>
                </div>
        </div>
    </main>
</body>

app/views/main/home.html.erb
<%= stylesheet_link_tag "style.css" %>
<br>
<br>
<body>
  <main>
    <div class="container text-center">
      <h2 class="line-1 anim-typewriter">Full Stack Developer</h2>
    </div>
    <div id="projects">
      <div class="container">
        <h1 class="text-center aboutHeading">DEVELOPMENT</h1>
        <br>
        <div class="container-fluid text-center">
            <div class="row">
                <div class="col-sm-12 ">
                  <%= image_tag "intro.gif" %>
                </div>
            </div>
        </div>
        <div class="row pt-5 m-auto" id="projectCards">
          <div class="col-md-6 col-lg-4 pb-3">
            <div class="card card-custom bg-white border-white border-0">
              <div class="card-custom-img" id="project1"></div>
              <a href="#" target="_blank" class="grow">
                <div class="card-custom-avatar">
                  <img class="img-fluid" src="https://1.bp.blogspot.com/-sqAjIvOtpXI/XYoCmqOyMwI/AAAAAAAAJig/CowR8wgEauEs-RXN2IPmLYkC7NHoHuA3gCLcBGAsYHQ/s1600/node-js-logo.png" alt="Avatar" />
                </div>
              </a>
              <div class="card-body" style="overflow-y: auto">
                <h4 class="card-title">NODE JS / MYSQL</h4>
                <p class="card-text">Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. It allows JavaScript on the server side, which enables building server-side applications with JavaScript.</p>
              </div>
              <div class="card-footer" style="background: inherit; border-color: inherit;">
                <a href="#" class="btn btn-info" target="_blank">View Live</a>
                <a href="#" class="btn btn-outline-primary">Read More</a>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 pb-3">
            <div class="card card-custom bg-white border-white border-0">
              <div class="card-custom-img" id="project2"></div>
              <a href="#" target="_blank" class="grow">
                <div class="card-custom-avatar">
                  <img class="img-fluid" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/6e0d9853-1604-498d-b94c-4eccb3515a9e/d9cvdyf-75d40ed4-469d-41ce-8db6-6ecfa6b4df96.png/v1/fill/w_1600,h_1600,strp/concept_logo___ruby_by_ssaazz_d9cvdyf-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTYwMCIsInBhdGgiOiJcL2ZcLzZlMGQ5ODUzLTE2MDQtNDk4ZC1iOTRjLTRlY2NiMzUxNWE5ZVwvZDljdmR5Zi03NWQ0MGVkNC00NjlkLTQxY2UtOGRiNi02ZWNmYTZiNGRmOTYucG5nIiwid2lkdGgiOiI8PTE2MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.caO2yajAMyq_yvj-kpxUM0lY-_vnGyqr1g7FiVoP_w8" alt="Avatar" />
                </div>
              </a>
              <div class="card-body" style="overflow-y: auto">
                <h4 class="card-title">Ruby / RAILS</h4>
                <p class="card-text">Rails, or Ruby on Rails, is a web application framework written in the Ruby programming language. It is used for building web applications and websites.</p>
              </div>
              <div class="card-footer" style="background: inherit; border-color: inherit;">
                <a href="#" class="btn btn-info">View Live</a>
                <button type="button" class="btn btn-outline-primary">Read More</button>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 pb-3">
            <div class="card card-custom bg-white border-white border-0">
              <div class="card-custom-img" id="portfolio"></div>
              <a href="#">
                <div class="card-custom-avatar">
                  <img class="img-fluid" src="https://s3.amazonaws.com/blog.invisionapp.com/uploads/2017/10/design-systems-atlassian.png" alt="Avatar" />
                </div>
              </a>
              <div class="card-body" style="overflow-y: auto">
                <h4 class="card-title">SYSTEM ARCHITECTURE</h4>
                <p class="card-text">System architecture is the high-level design of a system, which specifies the structure and behavior of the system as a whole. It defines the relationships and interactions between different components and subsystems within the system, as well as the interfaces and protocols for communication between them.</p>
              </div>
              <div class="card-footer" style="background: inherit; border-color: inherit;">
                <a href="#" class="btn btn-info">View Live</a>
                <button type="button" class="btn btn-outline-primary">Read More</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
</html>

<!--
<div class="container">
    <h2>Categories</h2>
    <hr>
    <% @categories.each do | category|%>
    <%= category.id %>
    <%= category.name %>
    <hr>
    <% end %>
</div>
-->